AnimalShelter/Models/Animal.cs
using System;

namespace AnimalShelter.Models 
{
  public class Animal
  {
    public string Name { get; set; }
    public string Species { get; set; }
    public string Breed { get; set; }
    public int Age { get; set; }
    public DateTime CheckIn { get; set; }
    public bool Available { get; set; }
    public int AnimalId { get; set; }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {
    public DbSet<Shelter> Shelters { get; set; }
    public DbSet<Animal> Animals { get; set; }

    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Models/Shelter.cs
using System.Collections.Generic;

namespace AnimalShelter.Models
{
  public class Shelter
  {
    public int ShelterId { get; set; }
    public string Business { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public List<Animal> Animals { get; set; }

  }
}

AnimalShelter/Controllers/AnimalsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using AnimalShelter.Models;
using System.Collections.Generic;
using System.Linq;

namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;
    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Animal> model = _db.Animals
      .OrderBy(animal => animal.Name)//can still treat it like sql data
      .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    //----------------
    [HttpPost]
    public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    //-----------------
    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    public ActionResult Date()
    {
      List<Animal> model = _db.Animals
      .OrderBy(animal => animal.CheckIn)
      .ToList();
      return View(model);
    }

    public ActionResult Dogs()
    {
      List<Animal> model = _db.Animals
      .Where(animal => animal.Species == "Dog")
      .ToList();
      return View(model);
    } 

    public ActionResult Edit(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }

    [HttpPost]
    public ActionResult Edit(Animal animal)
    {
      _db.Animals.Update(animal);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4>Add a new animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br />
  
  @Html.LabelFor(model => model.Species)
  @Html.TextBoxFor(model => model.Species)
  <br/>

  @Html.LabelFor(model => model.Breed)
  @Html.TextBoxFor(model => model.Breed)
  <br/>

  @Html.LabelFor(model => model.Age)
  @Html.TextBoxFor(model => model.Age)
  <br/>

  @Html.LabelFor(model => model.CheckIn)
  @Html.EditorFor(model => model.CheckIn) //date
  <br/>

  @Html.LabelFor(model => model.Available)
  @Html.CheckBoxFor(model => model.Available)
  <br/>

<input type="submit" value="Add new animal"/>

}

<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Date.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Our animals listed by Check In Date</h1>

@if (@Model.Count == 0)
{
  <h3>There are no animals in this shelter yet</h3>
} 

<ul>

@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"Name:{animal.Name}" + " " + $"Arrival:{animal.CheckIn}", "Details", new { id = animal.AnimalId })</li>
}

</ul>

<p>@Html.ActionLink("Add new animal", "Create")</p>
<p>@Html.ActionLink("List animals by Name", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Species): @Html.DisplayFor(model => model.Species)</h3>
<h3>@Html.DisplayNameFor(model => model.Breed): @Html.DisplayFor(model => model.Breed)</h3>
<h3>@Html.DisplayNameFor(model => model.Age): @Html.DisplayFor(model => model.Age)</h3>
<h3>@Html.DisplayNameFor(model => model.CheckIn): @Html.DisplayFor(model => model.CheckIn)</h3>
<h3>@Html.DisplayNameFor(model => model.Available): @Html.DisplayFor(model => model.Available)</h3>
<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Dogs.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Just Dogs</h1>

@if (@Model.Count == 0)
{
  <h3>There are no animals in this shelter yet</h3>
} 

<ul>

@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId })</li>
}

</ul>

<p>@Html.ActionLink("Add new animal", "Create")</p>
<p>@Html.ActionLink("View animals by Check In", "Date")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Animals</h1>

@if (@Model.Count == 0)
{
  <h3>There are no animals in this shelter yet</h3>
} 

<ul>

@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "Details", new { id = animal.AnimalId })</li>
}

</ul>

<p>@Html.ActionLink("Add new animal", "Create")</p>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the Animal Shelters Tracker!</h1>
<p>@Html.ActionLink("See all animals", "Index", "Animals")</p> <p>@Html.ActionLink("See all shelters", "Index", "Shelters")</p>
<p>@Html.ActionLink("View just dogs", "Dogs", "Animals")</p>

AnimalShelter/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Project Name!</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>